#!/usr/bin/env bash
# Script for backing up a databases
if [[ $# -eq 1 ]]; then
current_date=$(date '+%d-%m-%Y')
mysqldump -h localhost -u root -p"$1"  --all-databases  > backup.sql &&
echo "backup.sql"
gzip -c backup.sql > "$current_date".tar.gz
fi