#!/usr/bin/env bash
# config ngnix server to listen to port 80

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
