#!/usr/bin/env bash
# print To infinity and beyond indefinitely with delay 2 and handle different signal and save my pid in a file
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"
trap 'echo "Y U no love me?!"' SIGINT
trap "sudo rm -f /var/run/holbertonscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/holbertonscript.pid; echo I hate the kill command; exit" SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2

done