#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times in 9th print hi
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 9 ]
	then
		echo "Holberton School"
		echo "Hi"
	else
		echo "Holberton School"
	fi
  x=$((x + 1))
done
