#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
#Requirements:
#    nginx must be running as nginx user
#    nginx must be listening on all active IPs on port 8080
#    You cannot use apt-get remove
#    Write a Bash script that configures the container to fit the above requirements

sudo service nginx stop
sed -i -E 's/#user.+\;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/ -R
chmod +rw /etc/nginx/nginx.conf
for pid in $(pidof apache2); do
    kill "$pid"
done
su -c 'service nginx start' nginx
